config/routes.rb
Chergal::Application.routes.draw do

  root :to => 'site#index'
  get "site/index"
  get "static_pages/about"
  get "static_pages/contact"
  
  resources :categories

  resources :pics

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :pics
end

app/models/pic.rb
class Pic < ActiveRecord::Base

	mount_uploader :image, ImageUploader

	belongs_to :category

	validates :title, presence: true
	validates :title, uniqueness: true

	def self.search(search)
    if search
      find(:all, :conditions => ['title ILIKE ? OR author ILIKE ?', "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @pics = Pic.where(category_id: @category.id).paginate(:page => params[:page], :per_page => 6) #@pics = @category.pics
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]
  # GET /pics
  # GET /pics.json
  def index
    @pics = Pic.paginate(:page => params[:page], :per_page => 6)
  end

  # GET /pics/1
  # GET /pics/1.json
  def show
    @pic = Pic.find(params[:id])
    @pic.category = Category.find(params[:category_id]) if params[:category_id]
  end

  # GET /pics/new
  def new
    @pic = Pic.new
    @categories = Category.all
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics
  # POST /pics.json
  def create
    @pic = Pic.new(pic_params)
    
    respond_to do |format|
      if @pic.save
        format.html { redirect_to @pic, notice: 'Pic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pic }
      else
        format.html { render action: 'new' }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1
  # PATCH/PUT /pics/1.json
  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to @pic, notice: 'Pic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic.destroy
    respond_to do |format|
      format.html { redirect_to pics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.require(:pic).permit(:title, :description, :image, :category_id, :remote_image_url)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  	@picall = Pic.all
    @pics = @picall.order('created_at desc').reverse[0..2]
  end

def show
    @pic = Pic.find(params[:id])
    @pi
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.require(:pic).permit(:title, :description, :image, :remote_image_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def about
  	render 'static_pages/about'
  end

  def contact
  	render 'static_pages/contact'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, [1, 2, 3 ] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="page-header">
    <h1>Альбоми<small>    всі альбоми</small></h1>
</div>


    <% @categories.each do |category| %>
      <ul class="list-group">
        <style type="text/css">
            .list-group {
              max-width: 350px;
               }
            </style>

        <li class="list-group-item list-group-item-success"><%= link_to category.name,  category %></li>
        <li class="list-group-item"><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    <% end %>
 
<br>

<%= link_to 'Створити новий', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<br>


<%= will_paginate @pics %>
<div class='row'>
        <% @pics.each do |pic| %>
            <div class="col-sm-12 col-md-4">
              <div class="thumbnail">

                <% if (pic.image).blank? %>
                    <%= image_tag('blank.gif', class:'product_image', width:'300', height:'300') %>
                <% else %>
                    <%= link_to image_tag(pic.image, class:'product_image', width:'250', height:'250'), pic %>
                <% end %>

                <div class="caption">
                  <%= link_to pic.title, pic %><hr>
                  <p><%= sanitize( truncate pic.description, length: 100) %></p>
                </div>

              </div>
            </div>
        <% end %>


      </div>
 <%= will_paginate @pics %>     

app/views/layouts/_footer.html.erb
<footer id='footer' class="navbar">
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="col-md-1"></div>

    <div id='main_footer_menu' class="col-md-10">
      <div class="col-md-4">
        <ul class='footer_nav'>
          <li>Навчання</li>
          <li><%= link_to 'Головна сторінка', pics_path %></li>
        </ul>
      </div>

      <div id='central_footer_menu' class="col-md-4">
        <ul class='footer_nav'>
          <li>Література</li>
          <li><%= link_to 'Найпопулярніше', pics_path %></li>
          <li><%= link_to 'Всі фото', pics_path %></li>
        </ul>
      </div>

      <div class="col-md-4">
        <ul class='footer_nav'>
          <li>Фото</li>
          <li><%= link_to 'Рубрики', pics_path %></li>
          <li><%= link_to 'Остання тема', Pic.all.last %></li>
          <li><%= link_to 'Правила форуму', '#' %></li>
        </ul>
      </div>
    </div>

    <div class="col-md-1"></div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header id='header' class="navbar navbar-fixed-top">
  <nav class="navbar navbar-inverse" role="navigation">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" <%= link_to 'Chergallery', root_path %></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Головна', root_path %></li>
        <li><%= link_to 'Всі Фото', pics_path %></li>
        <li><%= link_to 'Альбоми', categories_path %></li>
      </ul>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chergal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>


  <div class="container">
  	
    <%= yield %>
  </div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pics/_form.html.erb
<%= form_for @pic, :html => {:multipart => true} do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %><br>

  </div>

  <div>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.label :remote_image_url, "or image URL" %>
    <%= f.text_field :remote_image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<!-- <div class="alle">
<div class="jumbotron"> -->
  <div class="page-header">
    <h1>Фотографії<small>    всі категорії</small></h1>
  </div>


<%= will_paginate %>
<div class='row'>
    <% @pics.each do |pic| %>
      <div class="col-sm-12 col-md-4">
          <div class="thumbnail">
            <% if (pic.image).blank?  %>
            <%= image_tag('blank.gif', style:'max-width:300px; max-height:300px') %>
            <% else %>
                <%= link_to image_tag(pic.image, style:'max-width:300px; max-height:300px' ), pic %>
            <% end %>

            <div class="caption">
              <%= link_to pic.title, pic %><hr>
              <p><%= sanitize( truncate pic.description, length: 101) %></p>
              <%= link_to 'Destroy', pic, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
      </div>
            <% end %>
            </div>

            <%= will_paginate %>
<div>
<%= link_to 'New Pic', new_pic_path %>
</div>
<!-- </div>
</div> -->

app/views/pics/new.html.erb
<h1>New pic</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<p id="notice"><%= notice %></p>


  <div id='central_col' class="col-md-7">
    <h4 class='level_h4'>Опис фото</h4>
    <div class='product_content'>
    	<p>
		  <strong>Назва:</strong>
		  <%= @pic.title %>
		</p>

      <div class='product_image'>
        <%= image_tag @pic.image_url, style:'max-width:1000px; max-height:700px' %>
      </div>

      <div class='info_content'>
        <h4><%= @pic.title %></h4>
        <hr>
        <p><b>Категорія: </b><%= link_to "Назад", @pic.category %></p>
        <p><b>Опис: </b><%= sanitize(@pic.description) %></p>
      </div>

    </div>
  </div>



<%= link_to 'Edit', edit_pic_path(@pic) %> |
<%= link_to 'Back', pics_path %>

app/views/site/_carousel.html.erb
<div id="store_carousel" class="carousel slide"><!-- class of slide for animation -->
  <div class="carousel-inner">
    <div class="item active">
        <style type="text/css">
  .item_active {
    max-width: 1200px;
    max-width: 480px;
    }
    </style>
      <!-- class of active since it's the first item -->
      <img src="images/555.jpg" alt="" />
      <div class="carousel-caption">
        <p>1Порекомендуйте</p>
      </div>
    </div>
    <div class="item">
      <img src="images/222.jpg" alt="first pic" />
      <div class="carousel-caption">
        <p>2Порекомендуйте</p>
      </div>
    </div>
    <div class="item">
      <img src="images/333.jpg" alt="second pic" />
      <div class="carousel-caption">
        <p>3Порекомендуйте</p>
      </div>
    </div>
    <div class="item">
      <img src="images/125.jpg" alt="third pic" />
      <div class="carousel-caption">
        <p>3Порекомендуйте</p>
      </div>
    </div>
  </div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#store_carousel" data-slide="prev">
      <span id='slide_glyph_left' class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="carousel-control right" href="#store_carousel" data-slide="next">
      <span id='slide_glyph_right' class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

app/views/site/index.html.erb
<h1>Ласкаво запрошую)</h1>
<%= render 'site/carousel' %>
<br>
<p>Зазвичай процес отримання фотографічного зображення включає в себе отримання дійсного зображення за допомогою оптичної системи на період експозиції і фіксації цього зображення за допомогою світлочутливої системи у вигляді електронного файлу або на фотоплівці. У випадку фотоплівки отримане зображення зазвичай є негативом, з якого потім отримують позитивне зображення при друкуванні світлин (фотографій) за допомогою фотозбільшувача. Як при отриманні негативу, так і при друкуванні фотографій, зображення спочатку латентне: його необхідно спершу проявити (за допомогою проявника), а потім — зафіксувати. Під час отримання електронної фотографії зображення від оптичної системи оцифровується.

Фотографія широко застосовується на виробництві, в наукових дослідженнях, для офіційних документів і в дозвіллі. Художня фотографія є окремим видом мистецтва. Фотографічний процес лежить в основі створення кіно.</p>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>